export const mockCellarSections = [
  {
    sectionId: "private-reserve",
    sectionName: "Private Reserve",
    theme: "Favorites",
    category: "favorites",
    description: "The bottles with history, gravity, and repeat invitations.",
    position: { x: 7, y: 16, width: 26, height: 32 },
    bottles: [
      {
        cellarEntryId: "entry-001",
        wineId: "wine-001",
        name: "Estate Cabernet Sauvignon",
        producer: "Aurelian Ridge",
        varietal: "Cabernet Sauvignon",
        type: "Red",
        vintage: 2018,
        region: "Napa Valley",
        country: "United States",
        rating: 5,
        notes: "Aurelian Ridge is a polished Napa Cabernet built for richer meals: black cherry, cassis, cedar, graphite, cocoa, and a quiet tobacco edge. The tannins are broad and confident, but the fruit stays composed rather than jammy, giving the bottle enough structure for ribeye, short ribs, and aged cheddar.",
        occasion: "Steak dinner",
        pairings: ["Ribeye", "Short ribs", "Aged cheddar"],
        imageUrl: "/images/cellar-wines/aurelian-ridge-estate-cabernet-sauvignon-2018.png",
        labelColor: "deep-red",
        favorite: true,
        dateAdded: "2026-04-01",
      },
      {
        cellarEntryId: "entry-002",
        wineId: "wine-002",
        name: "Gran Reserva Rioja",
        producer: "Bodega Las Lomas",
        varietal: "Tempranillo",
        type: "Red",
        vintage: 2012,
        region: "Rioja Alta",
        country: "Spain",
        rating: 5,
        notes: "Bodega Las Lomas shows the mellow, layered side of mature Rioja: dried cherry, red plum, tobacco, vanilla, cedar, and a little leather. It feels silky and old-world, with polished oak and enough savory depth to make lamb, manchego, and roasted mushrooms taste slower and more special.",
        occasion: "Anniversary",
        pairings: ["Lamb", "Manchego", "Roasted mushrooms"],
        imageUrl: "/images/cellar-wines/bodega-las-lomas-gran-reserva-rioja-2012.png",
        labelColor: "garnet",
        favorite: true,
        dateAdded: "2026-02-14",
      },
    ],
  },
  {
    sectionId: "steak-wall",
    sectionName: "Steak Wall",
    theme: "Best for Steak",
    category: "pairing",
    description: "Structured reds for char, fat, fire, and a very good knife.",
    position: { x: 37, y: 12, width: 27, height: 38 },
    bottles: [
      {
        cellarEntryId: "entry-003",
        wineId: "wine-003",
        name: "Old Vine Malbec",
        producer: "Finca Dorada",
        varietal: "Malbec",
        type: "Red",
        vintage: 2020,
        region: "Mendoza",
        country: "Argentina",
        rating: 4,
        notes: "Finca Dorada's Old Vine Malbec is plush and dark-fruited, with blackberry, plum, violet, espresso, and a warm cocoa note. The old-vine concentration gives it a generous middle, while the finish stays savory enough for grilled meat, burgers, and charred vegetables.",
        occasion: "Grill night",
        pairings: ["Skirt steak", "Burgers", "Charred vegetables"],
        imageUrl: "/images/cellar-wines/finca-dorada-old-vine-malbec-2020.png",
        labelColor: "plum",
        favorite: false,
        dateAdded: "2026-03-05",
      },
      {
        cellarEntryId: "entry-004",
        wineId: "wine-004",
        name: "Left Bank Rouge",
        producer: "Maison Corbeau",
        varietal: "Bordeaux Blend",
        type: "Red",
        vintage: 2017,
        region: "Bordeaux",
        country: "France",
        rating: 4,
        notes: "Maison Corbeau's Left Bank Rouge has the classic Bordeaux shape: cassis, black currant, cedar, graphite, dried herbs, and a savory mineral finish. The blend feels restrained and structured, making it a strong match for prime rib, lamb rack, truffle fries, and any meal that wants a serious red without excessive weight.",
        occasion: "Prime rib",
        pairings: ["Prime rib", "Lamb rack", "Truffle fries"],
        imageUrl: "/images/cellar-wines/maison-corbeau-left-bank-rouge-2017.png",
        labelColor: "black-gold",
        favorite: false,
        dateAdded: "2026-01-18",
      },
      {
        cellarEntryId: "entry-005",
        wineId: "wine-005",
        name: "Block 7 Syrah",
        producer: "Hearth & Vale",
        varietal: "Syrah",
        type: "Red",
        vintage: 2019,
        region: "Walla Walla",
        country: "United States",
        rating: 4,
        notes: "Hearth & Vale's Block 7 Syrah is savory and muscular, with blackberry, black olive, smoked pepper, cured meat, and a dark mineral edge. Firm structure and smoky aromatics make it feel built for a steakhouse table, especially pepper steak, short ribs, and blue cheese.",
        occasion: "Steakhouse",
        pairings: ["Pepper steak", "Short ribs", "Blue cheese"],
        imageUrl: "/images/cellar-wines/hearth-vale-block-7-syrah-2019.png",
        labelColor: "midnight",
        favorite: false,
        dateAdded: "2026-02-22",
      },
    ],
  },
  {
    sectionId: "date-night",
    sectionName: "Date Night",
    theme: "Low Light Bottles",
    category: "occasion",
    description: "Elegant wines for candlelight, conversation, and a slower pour.",
    position: { x: 68, y: 18, width: 24, height: 30 },
    bottles: [
      {
        cellarEntryId: "entry-006",
        wineId: "wine-006",
        name: "Willow Block Pinot Noir",
        producer: "Fogline Cellars",
        varietal: "Pinot Noir",
        type: "Red",
        vintage: 2021,
        region: "Willamette Valley",
        country: "United States",
        rating: 4,
        notes: "Fogline Cellars' Willow Block Pinot Noir is delicate but not thin, leading with wild strawberry, red cherry, tea leaf, rose petal, and soft forest-floor savor. Its gentle tannin and bright acidity make it a candlelight bottle for roast chicken, mushroom risotto, or salmon.",
        occasion: "Date night",
        pairings: ["Roast chicken", "Mushroom risotto", "Salmon"],
        imageUrl: "/images/cellar-wines/fogline-cellars-willow-block-pinot-noir-2021.png",
        labelColor: "ruby",
        favorite: false,
        dateAdded: "2026-04-10",
      },
      {
        cellarEntryId: "entry-007",
        wineId: "wine-007",
        name: "Brut Reserve",
        producer: "Maison Veyrac",
        varietal: "Chardonnay / Pinot Noir",
        type: "Sparkling",
        vintage: 2016,
        region: "Champagne",
        country: "France",
        rating: 5,
        notes: "Maison Veyrac Brut Reserve is a composed Champagne-style bottle with brioche, lemon curd, almond, green apple, and a fine mineral snap. The bubbles feel creamy but precise, so it can handle oysters, fried chicken, triple cream, and celebratory pours without becoming sweet or heavy.",
        occasion: "Celebration",
        pairings: ["Oysters", "Fried chicken", "Triple cream"],
        imageUrl: "/images/cellar-wines/maison-veyrac-brut-reserve-2016.png",
        labelColor: "champagne",
        favorite: true,
        dateAdded: "2026-02-01",
      },
    ],
  },
  {
    sectionId: "gift-cellar",
    sectionName: "Gifts & Celebrations",
    theme: "Bring or Send",
    category: "celebration",
    description: "Bottles with ceremony built in, from thank-yous to milestones.",
    position: { x: 17, y: 58, width: 31, height: 28 },
    bottles: [
      {
        cellarEntryId: "entry-008",
        wineId: "wine-008",
        name: "Sancerre Les Pierres",
        producer: "Domaine Clarette",
        varietal: "Sauvignon Blanc",
        type: "White",
        vintage: 2022,
        region: "Loire Valley",
        country: "France",
        rating: 4,
        notes: "Domaine Clarette's Sancerre Les Pierres is all lift and limestone: lime zest, grapefruit peel, wet stone, white flowers, and fresh herbs. It is crisp, dry, and sharply refreshing, which makes it ideal as a host gift or with goat cheese, shellfish, and spring vegetables.",
        occasion: "Host gift",
        pairings: ["Goat cheese", "Shellfish", "Spring vegetables"],
        imageUrl: "/images/cellar-wines/domaine-clarette-sancerre-les-pierres-2022.png",
        labelColor: "ivory",
        favorite: false,
        dateAdded: "2026-04-13",
      },
      {
        cellarEntryId: "entry-009",
        wineId: "wine-009",
        name: "Late Harvest Gold",
        producer: "Sunmere Estate",
        varietal: "Semillon",
        type: "Dessert",
        vintage: 2018,
        region: "Napa Valley",
        country: "United States",
        rating: 4,
        notes: "Sunmere Estate's Late Harvest Gold is a glossy dessert wine with apricot, honey, saffron, orange marmalade, and a polished sweetness that still feels controlled. It is best poured in small glasses with cheesecake, foie gras, blue cheese, or a birthday dessert that needs a golden finish.",
        occasion: "Birthday",
        pairings: ["Cheesecake", "Foie gras", "Blue cheese"],
        imageUrl: "/images/cellar-wines/sunmere-estate-late-harvest-gold-2018.png",
        labelColor: "gold",
        favorite: false,
        dateAdded: "2026-03-20",
      },
    ],
  },
  {
    sectionId: "rare-vintages",
    sectionName: "Rare Vintages",
    theme: "Hidden Room",
    category: "rare",
    description: "Older, limited, or quietly collectible bottles worth slowing down for.",
    position: { x: 54, y: 58, width: 30, height: 28 },
    bottles: [
      {
        cellarEntryId: "entry-010",
        wineId: "wine-010",
        name: "Library Barolo",
        producer: "Casa Velluto",
        varietal: "Nebbiolo",
        type: "Red",
        vintage: 2010,
        region: "Piedmont",
        country: "Italy",
        rating: 5,
        notes: "Casa Velluto's Library Barolo is the quiet collector bottle in the room: rose, tar, dried cherry, leather, anise, and long tannic architecture. The 2010 vintage profile feels mature and contemplative, built for truffle pasta, braised beef, aged parmesan, and a dinner that can move slowly.",
        occasion: "Collector dinner",
        pairings: ["Truffle pasta", "Braised beef", "Aged parmesan"],
        imageUrl: "/images/cellar-wines/casa-velluto-library-barolo-2010.png",
        labelColor: "aged-paper",
        favorite: true,
        dateAdded: "2025-12-18",
      },
      {
        cellarEntryId: "entry-011",
        wineId: "wine-011",
        name: "Single Vineyard Brunello",
        producer: "Tenuta Rocca Scura",
        varietal: "Sangiovese",
        type: "Red",
        vintage: 2013,
        region: "Montalcino",
        country: "Italy",
        rating: 4,
        notes: "Tenuta Rocca Scura's Single Vineyard Brunello carries sour cherry, cedar, dried herbs, balsamic lift, and confident Sangiovese acidity. It is structured without being blunt, making it a natural fit for osso buco, porcini, pecorino, and holiday dinners with a little ceremony.",
        occasion: "Holiday dinner",
        pairings: ["Osso buco", "Porcini", "Pecorino"],
        imageUrl: "/images/cellar-wines/tenuta-rocca-scura-single-vineyard-brunello-2013.png",
        labelColor: "terracotta",
        favorite: false,
        dateAdded: "2026-01-04",
      },
    ],
  },
];
