export const mockCellarSections = [
  {
    sectionId: "private-reserve",
    sectionName: "Private Reserve",
    theme: "Favorites",
    category: "favorites",
    description: "The bottles with history, gravity, and repeat invitations.",
    position: { x: 7, y: 16, width: 26, height: 32 },
    bottles: [
      {
        cellarEntryId: "entry-001",
        wineId: "wine-001",
        name: "Estate Cabernet Sauvignon",
        producer: "Aurelian Ridge",
        varietal: "Cabernet Sauvignon",
        type: "Red",
        vintage: 2018,
        region: "Napa Valley",
        country: "United States",
        rating: 5,
        notes: "Black cherry, cedar, graphite, and a long cocoa finish.",
        occasion: "Steak dinner",
        pairings: ["Ribeye", "Short ribs", "Aged cheddar"],
        imageUrl: null,
        labelColor: "deep-red",
        favorite: true,
        dateAdded: "2026-04-01",
      },
      {
        cellarEntryId: "entry-002",
        wineId: "wine-002",
        name: "Gran Reserva Rioja",
        producer: "Bodega Las Lomas",
        varietal: "Tempranillo",
        type: "Red",
        vintage: 2012,
        region: "Rioja Alta",
        country: "Spain",
        rating: 5,
        notes: "Dried cherry, tobacco, vanilla, and polished old-world texture.",
        occasion: "Anniversary",
        pairings: ["Lamb", "Manchego", "Roasted mushrooms"],
        imageUrl: null,
        labelColor: "garnet",
        favorite: true,
        dateAdded: "2026-02-14",
      },
    ],
  },
  {
    sectionId: "steak-wall",
    sectionName: "Steak Wall",
    theme: "Best for Steak",
    category: "pairing",
    description: "Structured reds for char, fat, fire, and a very good knife.",
    position: { x: 37, y: 12, width: 27, height: 38 },
    bottles: [
      {
        cellarEntryId: "entry-003",
        wineId: "wine-003",
        name: "Old Vine Malbec",
        producer: "Finca Dorada",
        varietal: "Malbec",
        type: "Red",
        vintage: 2020,
        region: "Mendoza",
        country: "Argentina",
        rating: 4,
        notes: "Plum, violet, espresso, and plush tannin.",
        occasion: "Grill night",
        pairings: ["Skirt steak", "Burgers", "Charred vegetables"],
        imageUrl: null,
        labelColor: "plum",
        favorite: false,
        dateAdded: "2026-03-05",
      },
      {
        cellarEntryId: "entry-004",
        wineId: "wine-004",
        name: "Left Bank Rouge",
        producer: "Maison Corbeau",
        varietal: "Bordeaux Blend",
        type: "Red",
        vintage: 2017,
        region: "Bordeaux",
        country: "France",
        rating: 4,
        notes: "Cassis, cedar, graphite, and a savory finish.",
        occasion: "Prime rib",
        pairings: ["Prime rib", "Lamb rack", "Truffle fries"],
        imageUrl: null,
        labelColor: "black-gold",
        favorite: false,
        dateAdded: "2026-01-18",
      },
      {
        cellarEntryId: "entry-005",
        wineId: "wine-005",
        name: "Block 7 Syrah",
        producer: "Hearth & Vale",
        varietal: "Syrah",
        type: "Red",
        vintage: 2019,
        region: "Walla Walla",
        country: "United States",
        rating: 4,
        notes: "Black olive, blackberry, smoked pepper, and firm structure.",
        occasion: "Steakhouse",
        pairings: ["Pepper steak", "Short ribs", "Blue cheese"],
        imageUrl: null,
        labelColor: "midnight",
        favorite: false,
        dateAdded: "2026-02-22",
      },
    ],
  },
  {
    sectionId: "date-night",
    sectionName: "Date Night",
    theme: "Low Light Bottles",
    category: "occasion",
    description: "Elegant wines for candlelight, conversation, and a slower pour.",
    position: { x: 68, y: 18, width: 24, height: 30 },
    bottles: [
      {
        cellarEntryId: "entry-006",
        wineId: "wine-006",
        name: "Willow Block Pinot Noir",
        producer: "Fogline Cellars",
        varietal: "Pinot Noir",
        type: "Red",
        vintage: 2021,
        region: "Willamette Valley",
        country: "United States",
        rating: 4,
        notes: "Wild strawberry, tea leaf, and soft savory depth.",
        occasion: "Date night",
        pairings: ["Roast chicken", "Mushroom risotto", "Salmon"],
        imageUrl: null,
        labelColor: "ruby",
        favorite: false,
        dateAdded: "2026-04-10",
      },
      {
        cellarEntryId: "entry-007",
        wineId: "wine-007",
        name: "Brut Reserve",
        producer: "Maison Veyrac",
        varietal: "Chardonnay / Pinot Noir",
        type: "Sparkling",
        vintage: 2016,
        region: "Champagne",
        country: "France",
        rating: 5,
        notes: "Brioche, lemon curd, almond, and fine mineral tension.",
        occasion: "Celebration",
        pairings: ["Oysters", "Fried chicken", "Triple cream"],
        imageUrl: null,
        labelColor: "champagne",
        favorite: true,
        dateAdded: "2026-02-01",
      },
    ],
  },
  {
    sectionId: "gift-cellar",
    sectionName: "Gifts & Celebrations",
    theme: "Bring or Send",
    category: "celebration",
    description: "Bottles with ceremony built in, from thank-yous to milestones.",
    position: { x: 17, y: 58, width: 31, height: 28 },
    bottles: [
      {
        cellarEntryId: "entry-008",
        wineId: "wine-008",
        name: "Sancerre Les Pierres",
        producer: "Domaine Clarette",
        varietal: "Sauvignon Blanc",
        type: "White",
        vintage: 2022,
        region: "Loire Valley",
        country: "France",
        rating: 4,
        notes: "Lime zest, wet stone, and white flowers.",
        occasion: "Host gift",
        pairings: ["Goat cheese", "Shellfish", "Spring vegetables"],
        imageUrl: null,
        labelColor: "ivory",
        favorite: false,
        dateAdded: "2026-04-13",
      },
      {
        cellarEntryId: "entry-009",
        wineId: "wine-009",
        name: "Late Harvest Gold",
        producer: "Sunmere Estate",
        varietal: "Semillon",
        type: "Dessert",
        vintage: 2018,
        region: "Napa Valley",
        country: "United States",
        rating: 4,
        notes: "Apricot, saffron, honey, and polished sweetness.",
        occasion: "Birthday",
        pairings: ["Cheesecake", "Foie gras", "Blue cheese"],
        imageUrl: null,
        labelColor: "gold",
        favorite: false,
        dateAdded: "2026-03-20",
      },
    ],
  },
  {
    sectionId: "rare-vintages",
    sectionName: "Rare Vintages",
    theme: "Hidden Room",
    category: "rare",
    description: "Older, limited, or quietly collectible bottles worth slowing down for.",
    position: { x: 54, y: 58, width: 30, height: 28 },
    bottles: [
      {
        cellarEntryId: "entry-010",
        wineId: "wine-010",
        name: "Library Barolo",
        producer: "Casa Velluto",
        varietal: "Nebbiolo",
        type: "Red",
        vintage: 2010,
        region: "Piedmont",
        country: "Italy",
        rating: 5,
        notes: "Rose, tar, dried cherry, leather, and long tannic architecture.",
        occasion: "Collector dinner",
        pairings: ["Truffle pasta", "Braised beef", "Aged parmesan"],
        imageUrl: null,
        labelColor: "aged-paper",
        favorite: true,
        dateAdded: "2025-12-18",
      },
      {
        cellarEntryId: "entry-011",
        wineId: "wine-011",
        name: "Single Vineyard Brunello",
        producer: "Tenuta Rocca Scura",
        varietal: "Sangiovese",
        type: "Red",
        vintage: 2013,
        region: "Montalcino",
        country: "Italy",
        rating: 4,
        notes: "Sour cherry, cedar, balsamic lift, and confident acidity.",
        occasion: "Holiday dinner",
        pairings: ["Osso buco", "Porcini", "Pecorino"],
        imageUrl: null,
        labelColor: "terracotta",
        favorite: false,
        dateAdded: "2026-01-04",
      },
    ],
  },
];
